# Generated by Django 4.2.28

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0347_add_singleton_to_tenantsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCPAgentCostSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("cluster_id", models.TextField()),
                ("cluster_alias", models.TextField(null=True)),
                ("namespace", models.CharField(max_length=253, null=True)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("agent_name", models.CharField(max_length=253, null=True)),
                ("agent_id", models.CharField(max_length=253, null=True)),
                ("model_name", models.CharField(max_length=253, null=True)),
                ("input_tokens", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("output_tokens", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cache_read_tokens", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("total_tokens", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("llm_call_count", models.IntegerField(null=True)),
                ("tool_call_count", models.IntegerField(null=True)),
                ("invocation_count", models.IntegerField(null=True)),
                ("avg_duration_seconds", models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ("cost_model_agent_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cost_model_rate_type", models.TextField(null=True)),
                ("raw_currency", models.TextField(null=True)),
                (
                    "cost_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.openshiftcostcategory",
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.tenantapiprovider",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_ocp_agent_cost_summary_p",
                "indexes": [
                    models.Index(fields=["usage_start"], name="ocpagentcost_usage_start"),
                    models.Index(fields=["cluster_id"], name="ocpagentcost_cluster_idx"),
                    models.Index(fields=["namespace"], name="ocpagentcost_namespace_idx"),
                    models.Index(fields=["agent_name"], name="ocpagentcost_agent_idx"),
                ],
            },
        ),
    ]
